//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentsExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public int id { get; set; }
        public string ТипАгента { get; set; }
        public Nullable<int> IdType { get; set; }
        public string НаименованиеАгента { get; set; }
        public string ЭлектроннаяПочтаАгента { get; set; }
        public string ТелефонАгента { get; set; }
        public string ЛоготипАгента { get; set; }
        public string ЮридическийАдрес { get; set; }
        public Nullable<int> Приоритет { get; set; }
        public string Директор { get; set; }
        public Nullable<long> ИНН { get; set; }
        public Nullable<long> КПП { get; set; }
    
        public virtual TypeAget TypeAget { get; set; }
    }
}
