//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentsExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int id { get; set; }
        public string Продукция { get; set; }
        public Nullable<int> idПродукции { get; set; }
        public string НаименованиеАгента { get; set; }
        public Nullable<int> IDAgent { get; set; }
        public Nullable<System.DateTime> Датареализации { get; set; }
        public Nullable<double> Количествопродукции { get; set; }
    
        public virtual ProductShort ProductShort { get; set; }
    }
}
