//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentsExamen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductShort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductShort()
        {
            this.ProductSale = new HashSet<ProductSale>();
        }
    
        public int id { get; set; }
        public string НаименованиеПродукции { get; set; }
        public string ТипПродукции { get; set; }
        public Nullable<int> IdТипаПродукции { get; set; }
        public Nullable<double> Артикул { get; set; }
        public Nullable<double> КоличествоЧеловекДляПроизводства { get; set; }
        public Nullable<double> НомерЦехаПроизводства { get; set; }
        public Nullable<double> МинимальнаяЦенаДляАгента { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
